<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Projetos de Análise de Dados com Linguagem Python</font>
### <font color='blue'>Projeto 5 - Técnicas de Encoding Para Modelagem Preditiva</font>

## Pacotes Python Usados no Projeto

In [1]:
!pip install -q -U watermark

In [2]:
# Imports
import joblib
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import warnings
warnings.filterwarnings("ignore")

In [3]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

## Carregando os Dados

In [4]:
# Carrega os dados
dados = pd.read_csv('dataset.csv')

In [5]:
# Shape
dados.shape

(13, 4)

In [6]:
# Visualiza os dados
dados

             Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0   Volkswagen Polo         79000        18000              6
1   Volkswagen Polo         65000        34000              3
2   Volkswagen Polo         57000        26100              5
3   Volkswagen Polo         72500        40000              2
4   Volkswagen Polo         44000        31500              4
5    Chevrolet Onix         69000        29400              5
6    Chevrolet Onix         62000        32000              5
7    Chevrolet Onix         61000        19300              6
8    Chevrolet Onix         71000        12000              8
9      Hyundai HB20         64000        22000              6
10     Hyundai HB20         81000        20000              7
11     Hyundai HB20         73000        21000              7
12     Hyundai HB20         57000        33000              5

In [7]:
# Tipos de dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Modelo         13 non-null     object
 1   Kilometragem   13 non-null     int64
 2   Preco_Venda    13 non-null     int64
 3   Idade_Veiculo  13 non-null     int64
dtypes: int64(3), object(1)
memory usage: 548.0+ bytes

> Pergunta: Qual a técnica ideal de encoding para criar o melhor modelo preditivo possível?

## Aplicando One-Hot-Encoding

https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

In [8]:
# Dataset original
dados

             Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0   Volkswagen Polo         79000        18000              6
1   Volkswagen Polo         65000        34000              3
2   Volkswagen Polo         57000        26100              5
3   Volkswagen Polo         72500        40000              2
4   Volkswagen Polo         44000        31500              4
5    Chevrolet Onix         69000        29400              5
6    Chevrolet Onix         62000        32000              5
7    Chevrolet Onix         61000        19300              6
8    Chevrolet Onix         71000        12000              8
9      Hyundai HB20         64000        22000              6
10     Hyundai HB20         81000        20000              7
11     Hyundai HB20         73000        21000              7
12     Hyundai HB20         57000        33000              5

In [9]:
# Obtém as variáveis dummy
df_dummies = pd.get_dummies(dados['Modelo'])

In [10]:
# Variáveis dummy
df_dummies

    Chevrolet Onix  Hyundai HB20  Volkswagen Polo
0            False         False             True
1            False         False             True
2            False         False             True
3            False         False             True
4            False         False             True
5             True         False            False
6             True         False            False
7             True         False            False
8             True         False            False
9            False          True            False
10           False          True            False
11           False          True            False
12           False          True            False

In [11]:
# Concatenamos os dataframes
df = pd.concat([dados, df_dummies], axis = 'columns')

In [12]:
df

,Modelo,Kilometragem,Preco_Venda,Idade_Veiculo,Chevrolet Onix,Hyundai HB20,Volkswagen Polo
0,Volkswagen Polo,79000,18000,6,False,False,True
1,Volkswagen Polo,65000,34000,3,False,False,True
2,Volkswagen Polo,57000,26100,5,False,False,True
3,Volkswagen Polo,72500,40000,2,False,False,True
4,Volkswagen Polo,44000,31500,4,False,False,True
5,Chevrolet Onix,69000,29400,5,True,False,False
6,Chevrolet Onix,62000,32000,5,True,False,False
7,Chevrolet Onix,61000,19300,6,True,False,False
8,Chevrolet Onix,71000,12000,8,True,False,False
9,Hyundai HB20,64000,22000,6,False,True,False
10,Hyundai HB20,81000,20000,7,False,True,False
11,Hyundai HB20,73000,21000,7,False,True,False
12,Hyundai HB20,57000,33000,5,False,True,False

In [13]:
# Drop da coluna categórica
newdf = df.drop(['Modelo'], axis = 1)

In [14]:
newdf

,Kilometragem,Preco_Venda,Idade_Veiculo,Chevrolet Onix,Hyundai HB20,Volkswagen Polo
0,79000,18000,6,False,False,True
1,65000,34000,3,False,False,True
2,57000,26100,5,False,False,True
3,72500,40000,2,False,False,True
4,44000,31500,4,False,False,True
5,69000,29400,5,True,False,False
6,62000,32000,5,True,False,False
7,61000,19300,6,True,False,False
8,71000,12000,8,True,False,False
9,64000,22000,6,False,True,False
10,81000,20000,7,False,True,False
11,73000,21000,7,False,True,False
12,57000,33000,5,False,True,False

In [15]:
# Define os valores de X
x = newdf.drop('Preco_Venda', axis = 1)

In [16]:
x

    Kilometragem  Idade_Veiculo  Chevrolet Onix  Hyundai HB20  Volkswagen Polo
0          79000              6           False         False             True
1          65000              3           False         False             True
2          57000              5           False         False             True
3          72500              2           False         False             True
4          44000              4           False         False             True
5          69000              5            True         False            False
6          62000              5            True         False            False
7          61000              6            True         False            False
8          71000              8            True         False            False
9          64000              6           False          True            False
10         81000              7           False          True            False
11         73000              7           False          True            False
12         57000              5           False          True            False

In [17]:
# Define os valores de y
y = newdf['Preco_Venda']

In [18]:
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Preco_Venda, dtype: int64

In [19]:
# Cria o modelo
modelo_dsa_v1 = linear_model.LinearRegression()

In [20]:
# Treina o modelo
modelo_dsa_v1.fit(x,y)

LinearRegression()

In [21]:
# Previsões do modelo
modelo_dsa_v1.predict(x)

array([18105.0215775 , 35327.25262423, 24783.14553092, 40410.02746228,
       30974.55280508, 28487.61326992, 28866.17068713, 23431.87824739,
       11914.33779555, 25628.97126508, 19221.24546681, 19653.88251505,
       31495.90075306])

In [22]:
# Uma previsão
modelo_dsa_v1.predict([[7000,4,0,0,1]])

array([32975.49915317])

In [23]:
# Uma previsão
modelo_dsa_v1.predict([[45000,4,0,1,0]])

array([37633.22839618])

In [24]:
# Uma previsão
modelo_dsa_v1.predict([[86000,7,1,0,0]])

array([16591.51540088])

In [25]:
# Acurácia do modelo
modelo_dsa_v1.score(x,y)

0.935561229062099

## Aplicando Label Encoding

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

In [26]:
# Cópia do dataframe original
df_car = dados

In [27]:
df_car

             Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0   Volkswagen Polo         79000        18000              6
1   Volkswagen Polo         65000        34000              3
2   Volkswagen Polo         57000        26100              5
3   Volkswagen Polo         72500        40000              2
4   Volkswagen Polo         44000        31500              4
5    Chevrolet Onix         69000        29400              5
6    Chevrolet Onix         62000        32000              5
7    Chevrolet Onix         61000        19300              6
8    Chevrolet Onix         71000        12000              8
9      Hyundai HB20         64000        22000              6
10     Hyundai HB20         81000        20000              7
11     Hyundai HB20         73000        21000              7
12     Hyundai HB20         57000        33000              5

In [28]:
# Cria o objeto encoder
le = LabelEncoder()

In [29]:
# Aplica o encoder
df_car['Modelo'] = le.fit_transform(df_car['Modelo'])

In [30]:
df_car

    Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0        2         79000        18000              6
1        2         65000        34000              3
2        2         57000        26100              5
3        2         72500        40000              2
4        2         44000        31500              4
5        0         69000        29400              5
6        0         62000        32000              5
7        0         61000        19300              6
8        0         71000        12000              8
9        1         64000        22000              6
10       1         81000        20000              7
11       1         73000        21000              7
12       1         57000        33000              5

In [31]:
# Define os valores de X
x = df_car[['Modelo', 'Kilometragem', 'Idade_Veiculo']].values

In [32]:
x

array([[    2, 79000,     6],
       [    2, 65000,     3],
       [    2, 57000,     5],
       [    2, 72500,     2],
       [    2, 44000,     4],
       [    0, 69000,     5],
       [    0, 62000,     5],
       [    0, 61000,     6],
       [    0, 71000,     8],
       [    1, 64000,     6],
       [    1, 81000,     7],
       [    1, 73000,     7],
       [    1, 57000,     5]])

In [33]:
# Define os valores de y
y = df_car['Preco_Venda']

In [34]:
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Preco_Venda, dtype: int64

In [35]:
# Cria a versão 2 do modelo
modelo_dsa_v2 = linear_model.LinearRegression()

In [36]:
# Treina o modelo
modelo_dsa_v2.fit(x,y)

LinearRegression()

In [37]:
# Faz previsões
modelo_dsa_v2.predict(x)

array([20594.96255322, 35709.41910683, 26372.80065489, 40228.36867645,
       31766.57106881, 29143.34538167, 29442.06469435, 24645.7329058 ,
       14540.97907838, 22876.39285467, 17311.92569064, 17653.31919085,
       28014.11814344])

In [38]:
# Uma previsão
modelo_dsa_v2.predict([[1,12500,2]])

array([44430.13741661])

In [39]:
# Calcula a acurácia
modelo_dsa_v2.score(x,y)

0.8757010116903793

## Aplicando One-Hot-Encoding com Transformer

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

In [40]:
# Cópia do dataframe original
df_car = dados

In [41]:
df_car

    Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0        2         79000        18000              6
1        2         65000        34000              3
2        2         57000        26100              5
3        2         72500        40000              2
4        2         44000        31500              4
5        0         69000        29400              5
6        0         62000        32000              5
7        0         61000        19300              6
8        0         71000        12000              8
9        1         64000        22000              6
10       1         81000        20000              7
11       1         73000        21000              7
12       1         57000        33000              5

In [42]:
# Cria o encoder com transformação
OHEncoder = ColumnTransformer([('Modelo', OneHotEncoder(), [0])], remainder = 'passthrough')

In [43]:
# Define os valores de X
x = df_car.drop('Preco_Venda', axis = 1)

In [44]:
x

    Modelo  Kilometragem  Idade_Veiculo
0        2         79000              6
1        2         65000              3
2        2         57000              5
3        2         72500              2
4        2         44000              4
5        0         69000              5
6        0         62000              5
7        0         61000              6
8        0         71000              8
9        1         64000              6
10       1         81000              7
11       1         73000              7
12       1         57000              5

<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->

In [45]:
# Define os valores de y
y = df_car['Preco_Venda']

In [46]:
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Preco_Venda, dtype: int64

In [47]:
# Aplica o encoder ao dataset x
X = OHEncoder.fit_transform(x)

In [48]:
X

array([[0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.50e+04, 3.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.25e+04, 2.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 4.40e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 6.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 6.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 6.10e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 6.40e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 8.10e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 7.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00]])

In [49]:
# Cria a versão 3 do modelo
modelo_dsa_v3 = linear_model.LinearRegression()

In [50]:
# Treina o modelo
modelo_dsa_v3.fit(X,y)

LinearRegression()

In [51]:
# Uma previsão do modelo (0, 0, 1, 14500, 3)
modelo_dsa_v3.predict([[0.00e+00,0.00e+00,1.00e+00,7.90e+04,6.00e+00]])

array([18105.02157751])

In [52]:
# Uma previsão do modelo
modelo_dsa_v3.predict([[0.00e+00,1.00e+00,0.00e+00,5.70e+04,8.00e+00]])

array([15030.78454074])

In [53]:
# Uma previsão do modelo
modelo_dsa_v3.score(X,y)

0.9355612290620993

## Salva o Modelo Treinado

In [54]:
acc_v1 = 0.9355612290620993

In [55]:
acc_v3 = 0.935561229062099

In [56]:
acc_v1 > acc_v3

True

Embora a versão 3 tenha uma performance ligeiramente inferior que a versão 1, usaremos a versão 3 pois ela cumpre a suposição do allgoritmo de Machine Learning de que os dados estão na mesma escala. A versão 2 pode ser descartada.

In [57]:
# Dump do melhor modelo
joblib.dump(modelo_dsa_v3, 'modelo_dsa_treinado.pkl')

['modelo_dsa_treinado.pkl']

## Conclusão

Qual a melhor técnica de encoding?

Não existe melhor técnica de forma isolada. Depende dos dados e do algoritmo de Machine Learning a ser usado. Sempre.

Para este conjunto de dados e para o algoritmo que usamos, a técnica de One-Hot-Encoding com Transformação de Coluna (na terceira versão do modelo) mostrou ser a mais efetiva e deveria ser usada no pré-processamento dos dados para modelagem preditiva.

In [58]:
%watermark -a "Data Science Academy"

Author: Data Science Academy

In [59]:
#%watermark -v -m

In [60]:
#%watermark --iversions

# Fim